#!/bin/bash
C="curl -s -m 5 -b /tmp/c.txt -c /tmp/c.txt -H Content-Type:application/json"
echo "1. fout wachtwoord:  $($C -X POST -d '{"wachtwoord":"fout"}' localhost:3000/api/login)"
echo "2. goed wachtwoord:  $($C -X POST -d '{"wachtwoord":"test"}' localhost:3000/api/login)"
echo "3. aanmaken:         $($C -X POST -d '{"voornaam":"Sanne","achternaam":"Mulder","bedrijf":"Mulder Coaching","plaats":"Capelle aan den IJssel","telefoon":"06-87654321","bron":"Netwerk"}' localhost:3000/api/contacten | head -c 120)"
echo "4. vervolgactie:     $($C -X PUT -d '{"voornaam":"Sanne","achternaam":"Mulder","bedrijf":"Mulder Coaching","vervolgdatum":"2026-07-09","gewenste_actie":"Demo geven"}' localhost:3000/api/contacten/1 | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d["vervolgdatum"],"|",d["gewenste_actie"])')"
echo "5. log toevoegen:    $($C -X POST -d '{"tekst":"Demo ingepland voor donderdag 10:00"}' localhost:3000/api/contacten/1/logboek | head -c 120)"
echo "6. kaart+logs:       $($C localhost:3000/api/contacten/1 | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d["contact"]["voornaam"],d["contact"]["achternaam"],"| logs:",len(d["logs"]),"| nieuwste:",d["logs"][0]["tekst"][:35])')"
echo "7. zoek coaching:    $($C 'localhost:3000/api/contacten?q=coaching' | python3 -c 'import json,sys;print(len(json.load(sys.stdin)),"treffers")')"
echo "8. zoek xyz:         $($C 'localhost:3000/api/contacten?q=xyz' | python3 -c 'import json,sys;print(len(json.load(sys.stdin)),"treffers")')"
echo "9. stats:            $($C localhost:3000/api/stats)"
echo "10. zonder login:    HTTP $(curl -s -m 5 -o /dev/null -w '%{http_code}' localhost:3000/api/contacten)"
echo "11. lege log:        $($C -X POST -d '{"tekst":"  "}' localhost:3000/api/contacten/1/logboek)"
echo "12. validatie:       $($C -X POST -d '{"voornaam":"","achternaam":""}' localhost:3000/api/contacten)"
