#!/bin/bash
C="curl -s -m 5 -b /tmp/c.txt -c /tmp/c.txt -H Content-Type:application/json"
echo "1. fout wachtwoord:  $($C -X POST -d '{"wachtwoord":"fout"}' localhost:3000/api/login)"
echo "2. goed wachtwoord:  $($C -X POST -d '{"wachtwoord":"test"}' localhost:3000/api/login)"
echo "3. bedrijf:          $($C -X POST -d '{"naam":"Mulder Coaching","straat":"Kerkstraat 1","postcode":"2903 BA","plaats":"Capelle aan den IJssel"}' localhost:3000/api/bedrijven | head -c 120)"
echo "4. aanmaken:         $($C -X POST -d '{"voornaam":"Sanne","achternaam":"Mulder","bedrijf_id":1,"telefoon":"06-87654321","bron":"Netwerk"}' localhost:3000/api/contacten | head -c 160)"
echo "5. vervolgactie:     $($C -X PUT -d '{"voornaam":"Sanne","achternaam":"Mulder","bedrijf_id":1,"vervolgdatum":"2026-07-09","gewenste_actie":"Demo geven"}' localhost:3000/api/contacten/1 | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d["vervolgdatum"],"|",d["gewenste_actie"],"|",d["bedrijf"])')"
echo "6. log toevoegen:    $($C -X POST -d '{"tekst":"Demo ingepland voor donderdag 10:00"}' localhost:3000/api/contacten/1/logboek | head -c 120)"
echo "7. kaart+logs:       $($C localhost:3000/api/contacten/1 | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d["contact"]["voornaam"],d["contact"]["achternaam"],"| logs:",len(d["logs"]),"| nieuwste:",d["logs"][0]["tekst"][:35])')"
echo "8. zoek coaching:    $($C 'localhost:3000/api/contacten?q=coaching' | python3 -c 'import json,sys;print(len(json.load(sys.stdin)),"treffers")')"
echo "9. zoek xyz:         $($C 'localhost:3000/api/contacten?q=xyz' | python3 -c 'import json,sys;print(len(json.load(sys.stdin)),"treffers")')"
echo "10. bedrijfkaart:    $($C localhost:3000/api/bedrijven/1 | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d["bedrijf"]["naam"],"| contactpersonen:",len(d["contactpersonen"]))')"
echo "11. acties:          $($C localhost:3000/api/acties | python3 -c 'import json,sys;print(len(json.load(sys.stdin)),"acties")')"
echo "12. actie toevoegen: $($C -X POST -d '{"naam":"Nieuwsbrief sturen"}' localhost:3000/api/acties | head -c 80)"
echo "13. dubbele actie:   $($C -X POST -d '{"naam":"Bellen"}' localhost:3000/api/acties)"
echo "14. stats:           $($C localhost:3000/api/stats)"
echo "15. zonder login:    HTTP $(curl -s -m 5 -o /dev/null -w '%{http_code}' localhost:3000/api/contacten)"
echo "16. lege log:        $($C -X POST -d '{"tekst":"  "}' localhost:3000/api/contacten/1/logboek)"
echo "17. validatie:       $($C -X POST -d '{"voornaam":"","achternaam":""}' localhost:3000/api/contacten)"
